apiVersion: v1
kind: Template
metadata:
  name: playbook-artifact-validator
objects:
- apiVersion: cloud.redhat.com/v1alpha1
  kind: ClowdApp
  metadata:
    name: playbook-artifact-validator
  spec:
    envName: ${ENV_NAME}
    deployments:
    - name: playbook-artifact-validator
      minReplicas: ${{MIN_REPLICAS}}
      web: false
      podSpec:
        image: ${IMAGE}:${IMAGE_TAG}
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /live
            port: 9000
            scheme: HTTP
          initialDelaySeconds: 10
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 5
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /ready
            port: 9000
            scheme: HTTP
          initialDelaySeconds: 10
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 5
        env:
          - name: LOG_LEVEL
            value: ${LOG_LEVEL}
          - name: CLOWDER_ENABLED
            value: "true"
        resources:
          limits:
            cpu: ${CPU_LIMIT}
            memory: ${MEMORY_LIMIT}
          requests:
            cpu: 250m
            memory: 256Mi
    kafkaTopics:
      - replicas: 3
        partitions: 16
        topicName: platform.upload.playbook
      - replicas: 3
        partitions: 16
        topicName: platform.upload.validation

parameters:
- name: LOG_LEVEL
  value: INFO
- description: Cpu limit of service
  name: CPU_LIMIT
  value: 500m
- description: memory limit of service
  name: MEMORY_LIMIT
  value: 512Mi
- description: min replicas
  name: MIN_REPLICAS
  value: "2"
- description: Image tag
  name: IMAGE_TAG
  required: true
- description: Image
  name: IMAGE
  required: true
  value: quay.io/cloudservices/playbook-artifact-validator
- description : ClowdEnvironment name
  name: ENV_NAME
  required: true

